### ISSUE TITLE
missing image: ![](img/ips/ipsdoc_2.png)

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_dev_mini_dataset#19]
Hi Joe:  please  note the [ips documentation(https://github.com/statonlab/tripal_dev_mini_dataset/blob/master/documentation/loading_IPS.md) has a missing link:  `![](img/ips/ipsdoc_2.png)`

**Comment by bradfordcondon** [comment]
All 3 images are missing.  most likely you didnt include the screenshot folder in your pull request?

**Comment by jwest60** [comment]
@bradfordcondon that's weird, i have no idea why the pictures don't seem to be merging. [the folder of images](https://github.com/jwest60/tripal_dev_mini_dataset/tree/load-interpro/documentation/img) is on my forked repo in the load-interpro branch, but when i make a pull request it says that everything is up-to-date

**Comment by bradfordcondon** [comment]
ok thanks.  I cloned it, rename the directory so t he commit would show up, merged, then renamed it back on master.  git weirdness, it happens.
