### ISSUE TITLE
Issue with data source 

### ISSUE THREAD

**Issue by Lupercal2** [statonlab/tripal_dev_mini_dataset#23]
https://github.com/statonlab/tripal_dev_mini_dataset/blob/master/documentation/loading_FASTA.md

## Issue
 The beginning part to create an analysis lacks information about the data course, the screenshot of the analysis with text in the fields also lacks Data Source. 
<img width="726" alt="slide 46 fixxed fixed" src="https://user-images.githubusercontent.com/37534829/37669686-de4ba276-2c3d-11e8-879f-46a23958c7cb.png">
<img width="580" alt="slide 46" src="https://user-images.githubusercontent.com/37534829/37669687-de591c4e-2c3d-11e8-86ae-6fd81196f87d.png">

**Comment by bradfordcondon** [comment]
Added data source to the text list.  I dont think we need to change the screenshot.
