### ISSUE TITLE
Compressed XML files - Unable to open on Windows

### ISSUE THREAD

**Issue by Lupercal2** [statonlab/tripal_dev_mini_dataset#24]
## Issue
Cannot get the XML files at this link https://github.com/statonlab/tripal_dev_mini_dataset/tree/master/blast_annotations to open on Windows. Cannot uncompress the files on windows.

**Comment by bradfordcondon** [comment]
Is there an error you are getting you can share?

**Comment by mestato** [comment]
They unzip and can be viewed with a text editor for me, so yes, an error would help.

**Comment by Lupercal2** [comment]
![slide 98](https://user-images.githubusercontent.com/37534829/37678598-e72e05d4-2c54-11e8-90ad-7666e4cee68d.png)
![slide 97](https://user-images.githubusercontent.com/37534829/37678599-e73d700a-2c54-11e8-8cb2-6ec9206fb0ea.png)
![slide 96](https://user-images.githubusercontent.com/37534829/37678600-e7582526-2c54-11e8-851c-424d0fccc210.png)

These are the errors I am getting. I tried opening the file by itself, tried unzipping the file using 7-zip, and tried just uploading the file to the tripal blast xml loader, (obviously didnt work cause it is .zip, but thought I'd try anyways)

**Comment by bradfordcondon** [comment]
the zip file is not corrupt.

Can you try opening it via right click ->open with 7zip instead of double clicking?

https://superuser.com/questions/518335/7-zip-cannot-open-file-on-double-click
