### ISSUE TITLE
Viewing BLAST Results - Step Missing. 

### ISSUE THREAD

**Issue by Lupercal2** [statonlab/tripal_dev_mini_dataset#25]
## Issue 

The steps explaining how to view the blast results with the mRNA content is missing a step. The step to check for new fields in "manage fields". Screen shots include the section referenced and a screenshot once the new fields have been added. 
<img width="1080" alt="slide 78" src="https://user-images.githubusercontent.com/37534829/37772024-bc961580-2daf-11e8-9493-05d6f82ded59.png">
<img width="666" alt="slide 78 fized" src="https://user-images.githubusercontent.com/37534829/37772025-bca22cc6-2daf-11e8-9c5d-de14e867f83c.png">

**Comment by bradfordcondon** [comment]
added suggestion thanks
