### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_dev_mini_dataset#6]
The documentation here needs to be good enough to publish.

As you load in the full dev dataset, it would be awesome if you could contribute guides to doing it.

Many cases the guides are *already written* but they are on the staton wiki.  for example:

https://github.com/mestato/statonlabprivate/wiki/Loading-a-Transcriptome-Geome-Tripal-3

In those cases, you can create a branch for that guide, add it, and make a PR.  Screenshots would be great.

**Comment by jwest60** [comment]
@bradfordcondon just finished the last of the edits. i moved the expression documentation from the biomaterials branch to the new expression branch and updated the fasta documentation and added screenshots for everything.

one of the things worth noting is that the only way i could get the screenshots to display the way they are is to hard link them, so that might be an issue moving forward?

**Comment by bradfordcondon** [comment]
great Joe!  

>the only way i could get the screenshots to display 

I'll have al ook... what I do is put them in like `/docs/img/`... and hten you can use relative path to link them...

**Comment by jwest60** [comment]
that works, but then the image will only display once the user clicks the link instead of showing it automatically, which is fine if that's the way you want to do it

**Comment by bradfordcondon** [comment]
please look at  https://github.com/tripal/tripal_analysis_expression/blob/master/README.md


files are linked as, for example

>> ![The Biosample property configuration tool](example_files/doc_images/biosample_prop_checker.png)

**Comment by jwest60** [comment]
Yeah, I just realized I used the wrong relative path the first time, I'm going to go back through and change all the links first thing tomorrow, shouldn't take too long.

**Comment by jwest60** [comment]
actually i just went ahead and did it now so all the links should now be relative paths

**Comment by bradfordcondon** [comment]
these have all been merged in.  Need to create a documentation index.
